### ISSUE TITLE
New version of MediatR 

### ISSUE THREAD

**Issue by pheurteladding** [Silvenga/MediatR.Ninject#1]
The new version of MediatR (5+) has a breaking change. MediatR.Ninject 1.0.0.5 is now not compatible with MediatR 5+.
`SingleInstanceFactory` and `MultiInstanceFactory` are now replaced by `ServiceFactory` (see in MediatRModule.cs file + [MediatR Migration-Guide 4.x-to-5.0](https://github.com/jbogard/MediatR/wiki/Migration-Guide-4.x-to-5.0))
Don't forget also to update the compatibility versions of MediatR.Ninject package. ;-)
And thank you for the plugin :-)

**Comment by Silvenga** [comment]
Ah, thanks for reminding me - the closing of sibbell.io is kind of complicating my workflow. I'll see if I have time this weekend to push out the changes, but I might be a little busy. Rest assured I'll get to it soon, I use this package for work projects - my team is planning an upgrade when we have some time.

**Comment by Silvenga** [comment]
@pheurteladding published via 2.0.1 - a upgrade of Ninject will be required. Please let me know if I missed something. Thanks for the issues.
