### ISSUE TITLE
New version of MediatR (v6.0.0)

### ISSUE THREAD

**Issue by pheurteladding** [Silvenga/MediatR.Ninject#2]
Happy new year!

The new version of MediatR (6+) has a breaking change. the nuget package of MediatR.Ninject 2.0.1 is now not compatible with the one of MediatR 6+.
MediatR.Ninject 2.0.1 targets versions of MediatR (>= 5.0.0 && < 6.0.0)

Here is the changelog of MediatR 6.0.0: https://github.com/jbogard/MediatR/releases/tag/v6.0.0

And thank you again for the plugin :-)

**Comment by Silvenga** [comment]
Thanks for the reminder @pheurteladding 😸 

I should have time to push out an upgrade this weekend. Feel free to ping me again if I forgot though.

**Comment by Silvenga** [comment]
@pheurteladding should be good now. Thanks for the issue!
