### ISSUE TITLE
Handler was not found for request of type 

### ISSUE THREAD

**Issue by murunwas** [Silvenga/MediatR.Ninject#3]
when I Bind my handlers using this example, `kernel.Bind<ExampleRequestHandler>.To<IRequestHandler<,>>;` i'm getting `Handler was not found for request of type MediatR.IRequestHandler`

**Comment by Silvenga** [comment]
Well that's because the read me was wrong - not sure how much sleep I had when I wrote that.

The correct signature for Ninject is:

```csharp
// Kernel.Bind<TService>().To<TImplementation>();
// So the correct usage is:
 Kernel.Bind<IRequestHandler<QueryFixture.Query, QueryFixture.Result>>().To<QueryFixtureHandler>();
```

Fixed the README. Let me know if you have any other questions.
